package com.example.courselingo.vision.analysis;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.example.courselingo.ai.record.domain.AiCallRecord;
import com.example.courselingo.ai.record.domain.AiCallRecordStatus;
import com.example.courselingo.ai.record.dto.AiCallRecordView;
import com.example.courselingo.ai.record.mapper.AiCallRecordMapper;
import com.example.courselingo.ai.record.service.AiCallRecordSanitizer;
import com.example.courselingo.ai.record.service.AiCallRecordService;
import com.example.courselingo.ai.record.service.AiCallRecordServiceImpl;
import com.example.courselingo.modelrouting.AiModelRoute;
import com.example.courselingo.modelrouting.AiModelRouter;
import com.example.courselingo.modelrouting.AiModelStage;
import com.example.courselingo.modelrouting.ModelCapability;
import com.example.courselingo.storage.StorageService;
import com.example.courselingo.vision.analysis.mapper.VideoKeyframeAnalysisMapper;
import com.example.courselingo.vision.keyframe.KeyframeSelectionReason;
import com.example.courselingo.vision.keyframe.VideoKeyframe;
import com.example.courselingo.vision.keyframe.mapper.VideoKeyframeMapper;
import com.example.courselingo.vision.ocr.VideoKeyframeOcr;
import com.example.courselingo.vision.ocr.mapper.VideoKeyframeOcrMapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;
import javax.sql.DataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

@SpringJUnitConfig(VisionAnalysisAiCallTransactionIntegrationTest.Config.class)
class VisionAnalysisAiCallTransactionIntegrationTest {

    @Autowired
    private VisionAnalysisService service;

    @Autowired
    private JdbcTemplate jdbc;

    @Autowired
    private FakeVisionState state;

    @Autowired
    private PlatformTransactionManager transactionManager;

    @BeforeEach
    void createSchema() {
        jdbc.execute("DROP TABLE IF EXISTS visual_probe");
        jdbc.execute("DROP TABLE IF EXISTS ai_call_record");
        jdbc.execute("""
            CREATE TABLE ai_call_record (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              task_id VARCHAR(64) NOT NULL,
              user_id BIGINT NOT NULL,
              call_type VARCHAR(32) NOT NULL,
              stage VARCHAR(64) NOT NULL,
              provider VARCHAR(64) NOT NULL,
              model VARCHAR(128) NOT NULL,
              status VARCHAR(32) NOT NULL,
              started_at TIMESTAMP NOT NULL,
              finished_at TIMESTAMP NULL,
              duration_millis BIGINT NULL,
              provider_duration_millis BIGINT NULL,
              batch_count INT NULL,
              retry_count INT NULL,
              prompt_tokens INT NULL,
              completion_tokens INT NULL,
              total_tokens INT NULL,
              input_units INT NULL,
              output_units INT NULL,
              request_fingerprint VARCHAR(128) NULL,
              response_fingerprint VARCHAR(128) NULL,
              error_code VARCHAR(64) NULL,
              error_message VARCHAR(512) NULL,
              retryable BOOLEAN NULL,
              created_at TIMESTAMP NOT NULL,
              updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbc.execute("CREATE TABLE visual_probe (keyframe_id BIGINT PRIMARY KEY, status VARCHAR(32) NOT NULL)");
        state.reset();
    }

    @Test
    void successfulFakeVisionTaskCreatesExactlyOneAccurateRecord() {
        state.keyframes = keyframes(2);

        VisionAnalysisScanResult result = service.scan("task_tx", 42L);

        assertThat(result.saved()).isEqualTo(2);
        assertThat(records()).singleElement().satisfies(record -> {
            assertThat(record.status()).isEqualTo(AiCallRecordStatus.SUCCEEDED);
            assertThat(record.batchCount()).isEqualTo(2);
            assertThat(record.inputUnits()).isEqualTo(2);
            assertThat(record.outputUnits()).isEqualTo(2);
            assertThat(record.providerDurationMillis()).isEqualTo(14L);
            assertThat(record.durationMillis()).isPositive();
        });
    }

    @Test
    void repeatableReadSnapshotCanCompleteRecordCreatedAfterSnapshot() {
        state.keyframes = keyframes(2);
        TransactionTemplate transaction = new TransactionTemplate(transactionManager);
        transaction.setIsolationLevel(TransactionDefinition.ISOLATION_REPEATABLE_READ);

        VisionAnalysisScanResult result = transaction.execute(status -> {
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ai_call_record", Integer.class)).isZero();
            return service.scan("task_tx", 42L);
        });

        assertThat(result).isNotNull();
        assertThat(result.saved()).isEqualTo(2);
        assertThat(records()).singleElement().satisfies(record -> {
            assertThat(record.status()).isEqualTo(AiCallRecordStatus.SUCCEEDED);
            assertThat(record.inputUnits()).isEqualTo(2);
            assertThat(record.outputUnits()).isEqualTo(2);
        });
    }

    @Test
    void committedVisionRowsAndAuditAreIndependentFromACallerRollback() {
        state.keyframes = keyframes(2);
        TransactionTemplate transaction = new TransactionTemplate(transactionManager);

        transaction.executeWithoutResult(status -> {
            VisionAnalysisScanResult result = service.scan("task_tx", 42L);
            assertThat(result.saved()).isEqualTo(2);
            status.setRollbackOnly();
        });

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM visual_probe", Integer.class)).isEqualTo(2);
        assertThat(records()).singleElement().satisfies(record ->
            assertThat(record.status()).isEqualTo(AiCallRecordStatus.SUCCEEDED)
        );
    }

    @Test
    void failedOuterVisionTransactionKeepsSanitizedFailedRecordAndRollsBackAnalysisRows() {
        state.keyframes = keyframes(1);
        state.failAnalysisInsert = true;

        assertThatThrownBy(() -> service.scan("task_tx", 42L))
            .isInstanceOf(IllegalStateException.class);

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM visual_probe", Integer.class)).isZero();
        assertThat(records()).singleElement().satisfies(record -> {
            assertThat(record.status()).isEqualTo(AiCallRecordStatus.FAILED);
            assertThat(record.durationMillis()).isPositive();
            assertThat(record.errorCode()).isEqualTo("VISION_ANALYSIS_FAILED");
            assertThat(record.errorMessage()).doesNotContain("objectKey", "token", "C:\\");
        });
    }

    @Test
    void oneFailedFrameProducesPartialSuccessWithFiveAttemptedAndFourOutputs() {
        state.keyframes = keyframes(5);
        state.providerFailureKeyframeId = 3L;

        VisionAnalysisScanResult result = service.scan("task_tx", 42L);

        assertThat(result.saved()).isEqualTo(5);
        assertThat(result.succeeded()).isEqualTo(4);
        assertThat(result.failed()).isEqualTo(1);
        assertThat(records()).singleElement().satisfies(record -> {
            assertThat(record.status()).isEqualTo(AiCallRecordStatus.PARTIAL_SUCCESS);
            assertThat(record.batchCount()).isEqualTo(5);
            assertThat(record.inputUnits()).isEqualTo(5);
            assertThat(record.outputUnits()).isEqualTo(4);
            assertThat(record.providerDurationMillis()).isEqualTo(28L);
        });
    }

    private List<AiCallRecordView> records() {
        return jdbc.query("SELECT * FROM ai_call_record ORDER BY id", (rs, rowNum) -> new AiCallRecordView(
            rs.getLong("id"), rs.getString("task_id"),
            com.example.courselingo.ai.record.domain.AiCallType.valueOf(rs.getString("call_type")),
            com.example.courselingo.ai.record.domain.AiCallStage.valueOf(rs.getString("stage")),
            rs.getString("provider"), rs.getString("model"),
            AiCallRecordStatus.valueOf(rs.getString("status")),
            rs.getTimestamp("started_at").toLocalDateTime(),
            rs.getTimestamp("finished_at") == null ? null : rs.getTimestamp("finished_at").toLocalDateTime(),
            nullableLong(rs, "duration_millis"), nullableLong(rs, "provider_duration_millis"),
            nullableInt(rs, "batch_count"), nullableInt(rs, "retry_count"),
            nullableInt(rs, "prompt_tokens"), nullableInt(rs, "completion_tokens"),
            nullableInt(rs, "total_tokens"), nullableInt(rs, "input_units"), nullableInt(rs, "output_units"),
            rs.getString("request_fingerprint"), rs.getString("response_fingerprint"),
            rs.getString("error_code"), rs.getString("error_message"),
            rs.getObject("retryable", Boolean.class),
            rs.getTimestamp("created_at").toLocalDateTime(), rs.getTimestamp("updated_at").toLocalDateTime()
        ));
    }

    private static Long nullableLong(java.sql.ResultSet rs, String column) throws java.sql.SQLException {
        long value = rs.getLong(column);
        return rs.wasNull() ? null : value;
    }

    private static Integer nullableInt(java.sql.ResultSet rs, String column) throws java.sql.SQLException {
        int value = rs.getInt(column);
        return rs.wasNull() ? null : value;
    }

    private static List<VideoKeyframe> keyframes(int count) {
        List<VideoKeyframe> result = new ArrayList<>();
        for (int index = 0; index < count; index++) {
            VideoKeyframe keyframe = new VideoKeyframe();
            keyframe.setId((long) index + 1L);
            keyframe.setTaskId("task_tx");
            keyframe.setUserId(42L);
            keyframe.setFrameIndex(index);
            keyframe.setTimestampMillis(index * 60_000L);
            keyframe.setSelectReason(KeyframeSelectionReason.CONTENT_CHANGE.name());
            keyframe.setObjectKey("fictional-frame-" + index);
            result.add(keyframe);
        }
        return result;
    }

    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    static class Config {

        @Bean
        DataSource dataSource() {
            return new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2)
                .setName("vision-ai-call-tx;MODE=MySQL;DB_CLOSE_DELAY=-1").build();
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        FakeVisionState fakeVisionState() {
            return new FakeVisionState();
        }

        @Bean
        AiCallRecordMapper aiCallRecordMapper(JdbcTemplate jdbc) {
            AiCallRecordMapper mapper = mock(AiCallRecordMapper.class);
            AtomicLong ids = new AtomicLong();
            when(mapper.insert(any(AiCallRecord.class))).thenAnswer(invocation -> {
                AiCallRecord row = invocation.getArgument(0);
                long id = ids.incrementAndGet();
                row.setId(id);
                return jdbc.update("""
                    INSERT INTO ai_call_record (
                      id, task_id, user_id, call_type, stage, provider, model, status, started_at,
                      input_units, request_fingerprint, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, id, row.getTaskId(), row.getUserId(), row.getCallType(), row.getStage(),
                    row.getProvider(), row.getModel(), row.getStatus(), row.getStartedAt(), row.getInputUnits(),
                    row.getRequestFingerprint(), row.getCreatedAt(), row.getUpdatedAt());
            });
            when(mapper.selectByIdTaskIdAndUserId(any(), any(), any())).thenAnswer(invocation -> {
                List<AiCallRecord> rows = jdbc.query(
                    "SELECT * FROM ai_call_record WHERE id=? AND task_id=? AND user_id=?",
                    (rs, rowNum) -> recordFrom(rs), invocation.getArgument(0), invocation.getArgument(1),
                    invocation.getArgument(2));
                return rows.isEmpty() ? null : rows.getFirst();
            });
            when(mapper.updateByIdTaskIdAndUserId(any(), any(), any(), any())).thenAnswer(invocation -> {
                AiCallRecord row = invocation.getArgument(0);
                return jdbc.update("""
                    UPDATE ai_call_record SET status=?, finished_at=?, duration_millis=?,
                      provider_duration_millis=COALESCE(?, provider_duration_millis),
                      batch_count=COALESCE(?, batch_count), retry_count=COALESCE(?, retry_count),
                      prompt_tokens=COALESCE(?, prompt_tokens), completion_tokens=COALESCE(?, completion_tokens),
                      total_tokens=COALESCE(?, total_tokens), input_units=COALESCE(?, input_units),
                      output_units=COALESCE(?, output_units), request_fingerprint=COALESCE(?, request_fingerprint),
                      response_fingerprint=COALESCE(?, response_fingerprint), error_code=?, error_message=?,
                      retryable=?, updated_at=? WHERE id=? AND task_id=? AND user_id=?
                    """, row.getStatus(), row.getFinishedAt(), row.getDurationMillis(),
                    row.getProviderDurationMillis(), row.getBatchCount(), row.getRetryCount(),
                    row.getPromptTokens(), row.getCompletionTokens(), row.getTotalTokens(), row.getInputUnits(),
                    row.getOutputUnits(), row.getRequestFingerprint(), row.getResponseFingerprint(),
                    row.getErrorCode(), row.getErrorMessage(), row.getRetryable(), row.getUpdatedAt(),
                    invocation.getArgument(1), invocation.getArgument(2), invocation.getArgument(3));
            });
            return mapper;
        }

        @Bean
        AiCallRecordService aiCallRecordService(AiCallRecordMapper mapper) {
            return new AiCallRecordServiceImpl(mapper, Clock.systemUTC(), new AiCallRecordSanitizer());
        }

        @Bean
        VisionAnalysisService visionAnalysisService(
            JdbcTemplate jdbc,
            FakeVisionState state,
            AiCallRecordService records,
            PlatformTransactionManager transactionManager
        ) {
            VideoKeyframeMapper keyframes = mock(VideoKeyframeMapper.class);
            when(keyframes.selectByTaskIdAndUserId(any(), any())).thenAnswer(ignored -> state.keyframes);
            VideoKeyframeOcrMapper ocr = mock(VideoKeyframeOcrMapper.class);
            when(ocr.selectByKeyframeIds(any(), any(), any())).thenReturn(List.<VideoKeyframeOcr>of());
            VideoKeyframeAnalysisMapper analyses = mock(VideoKeyframeAnalysisMapper.class);
            when(analyses.deleteByTaskIdAndUserId(any(), any())).thenAnswer(ignored -> jdbc.update("DELETE FROM visual_probe"));
            when(analyses.insert(any(VideoKeyframeAnalysis.class))).thenAnswer(invocation -> {
                VideoKeyframeAnalysis row = invocation.getArgument(0);
                int inserted = jdbc.update("INSERT INTO visual_probe (keyframe_id, status) VALUES (?, ?)",
                    row.getKeyframeId(), row.getStatus());
                if (state.failAnalysisInsert) {
                    throw new IllegalStateException("fictional persistence failure");
                }
                return inserted;
            });
            StorageService storage = mock(StorageService.class);
            when(storage.openObject(any())).thenReturn(new ByteArrayInputStream(
                "fictional image".getBytes(StandardCharsets.UTF_8)));
            VisionModelProvider provider = new VisionModelProvider() {
                @Override
                public String providerName() {
                    return "fake-vision";
                }

                @Override
                public VisionAnalysisResult analyze(VisionAnalysisRequest request) {
                    if (request.keyframeId().equals(state.providerFailureKeyframeId)) {
                        throw new IllegalStateException("fictional provider failure");
                    }
                    return new VisionAnalysisResult(
                        VisionAnalysisStatus.SUCCEEDED, "PPT", "fictional summary", List.of("title"),
                        providerName(), request.route().modelName(), 7L, null, null
                    );
                }
            };
            AiModelRouter router = mock(AiModelRouter.class);
            when(router.route(AiModelStage.VISION_FRAME_ANALYSIS)).thenReturn(new AiModelRoute(
                AiModelStage.VISION_FRAME_ANALYSIS, "fake", "Fake", "fake-vision", "https://invalid.test",
                "fictional-vl", "TEST_ONLY", EnumSet.of(ModelCapability.VISION, ModelCapability.JSON_OUTPUT),
                0.0d, 256, Duration.ofSeconds(1), 1
            ));
            VisionAnalysisProperties properties = new VisionAnalysisProperties();
            properties.setEnabled(true);
            properties.setMaxFramesTotal(10);
            properties.setMaxFramesPerMinute(10);
            properties.setSlideMaxFramesPerMinute(10);
            properties.setCodeOrTerminalMaxFramesPerMinute(10);
            properties.setVisualDemoMaxFramesPerMinute(10);
            properties.setTalkingOrLowInformationMaxFramesPerMinute(10);
            properties.setUnknownMaxFramesPerMinute(10);
            return new VisionAnalysisServiceImpl(
                keyframes, ocr, analyses, storage, provider, router, new HighValueKeyframeSelector(), properties,
                new ObjectMapper(), Clock.systemUTC(), null, null, records, transactionManager
            );
        }

        private static AiCallRecord recordFrom(java.sql.ResultSet rs) throws java.sql.SQLException {
            AiCallRecord row = new AiCallRecord();
            row.setId(rs.getLong("id"));
            row.setTaskId(rs.getString("task_id"));
            row.setUserId(rs.getLong("user_id"));
            row.setCallType(rs.getString("call_type"));
            row.setStage(rs.getString("stage"));
            row.setProvider(rs.getString("provider"));
            row.setModel(rs.getString("model"));
            row.setStatus(rs.getString("status"));
            row.setStartedAt(rs.getTimestamp("started_at").toLocalDateTime());
            row.setCreatedAt(rs.getTimestamp("created_at").toLocalDateTime());
            row.setUpdatedAt(rs.getTimestamp("updated_at").toLocalDateTime());
            return row;
        }
    }

    static final class FakeVisionState {
        private List<VideoKeyframe> keyframes = List.of();
        private Long providerFailureKeyframeId;
        private boolean failAnalysisInsert;

        private void reset() {
            keyframes = List.of();
            providerFailureKeyframeId = null;
            failAnalysisInsert = false;
        }
    }
}
