package com.example.courselingo.common.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

    COMMON_BAD_REQUEST("COMMON_BAD_REQUEST", "请求参数错误", HttpStatus.BAD_REQUEST),
    COMMON_UNAUTHORIZED("COMMON_UNAUTHORIZED", "未认证或认证已失效", HttpStatus.UNAUTHORIZED),
    COMMON_FORBIDDEN("COMMON_FORBIDDEN", "无权访问资源", HttpStatus.FORBIDDEN),
    COMMON_NOT_FOUND("COMMON_NOT_FOUND", "资源不存在", HttpStatus.NOT_FOUND),
    COMMON_VALIDATION_FAILED("COMMON_VALIDATION_FAILED", "请求参数校验失败", HttpStatus.BAD_REQUEST),
    COMMON_INTERNAL_ERROR("COMMON_INTERNAL_ERROR", "服务内部错误", HttpStatus.INTERNAL_SERVER_ERROR),

    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS", "登录凭据无效", HttpStatus.UNAUTHORIZED),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED", "访问令牌已过期", HttpStatus.UNAUTHORIZED),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID", "访问令牌无效", HttpStatus.UNAUTHORIZED),
    AUTH_USER_DISABLED("AUTH_USER_DISABLED", "用户已被禁用", HttpStatus.FORBIDDEN),
    AUTH_TOKEN_SIGN_FAILED("AUTH_TOKEN_SIGN_FAILED", "访问令牌签发失败", HttpStatus.INTERNAL_SERVER_ERROR),
    AUTH_REFRESH_TOKEN_INVALID("AUTH_REFRESH_TOKEN_INVALID", "刷新令牌无效", HttpStatus.UNAUTHORIZED),
    AUTH_REFRESH_TOKEN_REVOKED("AUTH_REFRESH_TOKEN_REVOKED", "刷新令牌已撤销", HttpStatus.UNAUTHORIZED),
    AUTH_EMAIL_ALREADY_EXISTS("AUTH_EMAIL_ALREADY_EXISTS", "邮箱已存在", HttpStatus.CONFLICT),
    AUTH_PASSWORD_WEAK("AUTH_PASSWORD_WEAK", "密码强度不符合要求", HttpStatus.BAD_REQUEST),

    UPLOAD_INVALID_EXTENSION("UPLOAD_INVALID_EXTENSION", "上传文件扩展名不允许", HttpStatus.BAD_REQUEST),
    UPLOAD_INVALID_FILENAME("UPLOAD_INVALID_FILENAME", "上传文件名不合法", HttpStatus.BAD_REQUEST),
    UPLOAD_INVALID_MD5("UPLOAD_INVALID_MD5", "上传文件 MD5 不合法", HttpStatus.BAD_REQUEST),
    UPLOAD_INVALID_CHUNK("UPLOAD_INVALID_CHUNK", "上传分片参数不合法", HttpStatus.BAD_REQUEST),
    UPLOAD_INVALID_SIGNATURE("UPLOAD_INVALID_SIGNATURE", "上传文件签名校验失败", HttpStatus.BAD_REQUEST),
    UPLOAD_CHUNK_OUT_OF_RANGE("UPLOAD_CHUNK_OUT_OF_RANGE", "上传分片序号超出范围", HttpStatus.BAD_REQUEST),
    UPLOAD_SESSION_NOT_FOUND("UPLOAD_SESSION_NOT_FOUND", "上传会话不存在", HttpStatus.NOT_FOUND),
    UPLOAD_SESSION_FORBIDDEN("UPLOAD_SESSION_FORBIDDEN", "无权访问上传会话", HttpStatus.FORBIDDEN),
    UPLOAD_INVALID_SESSION_ID("UPLOAD_INVALID_SESSION_ID", "上传会话 ID 不合法", HttpStatus.BAD_REQUEST),
    UPLOAD_EMPTY_CHUNK("UPLOAD_EMPTY_CHUNK", "上传分片不能为空", HttpStatus.BAD_REQUEST),
    UPLOAD_CHUNK_SAVE_FAILED("UPLOAD_CHUNK_SAVE_FAILED", "上传分片保存失败", HttpStatus.INTERNAL_SERVER_ERROR),
    UPLOAD_CHUNK_MISSING("UPLOAD_CHUNK_MISSING", "上传分片缺失", HttpStatus.BAD_REQUEST),
    UPLOAD_SESSION_STATUS_INVALID("UPLOAD_SESSION_STATUS_INVALID", "上传会话状态不允许当前操作", HttpStatus.CONFLICT),
    UPLOAD_SESSION_CREATE_FAILED("UPLOAD_SESSION_CREATE_FAILED", "创建上传会话失败", HttpStatus.INTERNAL_SERVER_ERROR),
    UPLOAD_ASSEMBLED_SIZE_MISMATCH("UPLOAD_ASSEMBLED_SIZE_MISMATCH", "合并文件大小校验失败", HttpStatus.CONFLICT),
    UPLOAD_ASSEMBLED_MD5_MISMATCH("UPLOAD_ASSEMBLED_MD5_MISMATCH", "合并文件 MD5 校验失败", HttpStatus.CONFLICT),
    UPLOAD_INVALID_VIDEO_HEADER("UPLOAD_INVALID_VIDEO_HEADER", "上传文件视频头校验失败", HttpStatus.BAD_REQUEST),
    UPLOAD_MERGE_FAILED("UPLOAD_MERGE_FAILED", "上传分片合并失败", HttpStatus.INTERNAL_SERVER_ERROR),

    STORAGE_INVALID_OBJECT_KEY("STORAGE_INVALID_OBJECT_KEY", "存储对象 key 不合法", HttpStatus.BAD_REQUEST),
    STORAGE_SOURCE_FILE_INVALID("STORAGE_SOURCE_FILE_INVALID", "存储源文件不合法", HttpStatus.BAD_REQUEST),
    STORAGE_OPERATION_FAILED("STORAGE_OPERATION_FAILED", "对象存储操作失败", HttpStatus.INTERNAL_SERVER_ERROR),
    STORAGE_CONFIGURATION_INVALID("STORAGE_CONFIGURATION_INVALID", "对象存储配置不合法", HttpStatus.INTERNAL_SERVER_ERROR),

    TASK_NOT_FOUND("TASK_NOT_FOUND", "任务不存在", HttpStatus.NOT_FOUND),
    TASK_NOT_OWNER("TASK_NOT_OWNER", "无权访问该任务", HttpStatus.FORBIDDEN),
    TASK_INVALID_STATUS("TASK_INVALID_STATUS", "任务状态不允许当前操作", HttpStatus.CONFLICT),
    TASK_RETRY_NOT_ALLOWED("TASK_RETRY_NOT_ALLOWED", "任务不允许重新分析", HttpStatus.CONFLICT),
    TASK_DELETE_NOT_ALLOWED("TASK_DELETE_NOT_ALLOWED", "存在仍在处理中的课程，请先取消处理后再删除", HttpStatus.CONFLICT),
    TASK_RATE_LIMITED("TASK_RATE_LIMITED", "任务创建过于频繁", HttpStatus.TOO_MANY_REQUESTS),
    TASK_DUPLICATE_CLAIMED("TASK_DUPLICATE_CLAIMED", "任务已被其他执行器领取", HttpStatus.CONFLICT),
    TASK_CLAIM_UNAVAILABLE("TASK_CLAIM_UNAVAILABLE", "任务领取状态暂时不可用", HttpStatus.SERVICE_UNAVAILABLE),
    TASK_RUNNER_EXECUTION_FAILED("TASK_RUNNER_EXECUTION_FAILED", "任务执行器执行失败", HttpStatus.INTERNAL_SERVER_ERROR),
    TASK_EXECUTOR_BUSY("TASK_EXECUTOR_BUSY", "任务执行器队列已满", HttpStatus.TOO_MANY_REQUESTS),
    TASK_EXECUTOR_TIMEOUT("TASK_EXECUTOR_TIMEOUT", "任务执行器执行超时", HttpStatus.GATEWAY_TIMEOUT),
    TASK_EXECUTOR_FAILED("TASK_EXECUTOR_FAILED", "任务执行器执行失败", HttpStatus.INTERNAL_SERVER_ERROR),
    TASK_EXECUTOR_SHUTDOWN("TASK_EXECUTOR_SHUTDOWN", "任务执行器已关闭", HttpStatus.SERVICE_UNAVAILABLE),
    TASK_EXECUTOR_CONFIGURATION_INVALID("TASK_EXECUTOR_CONFIGURATION_INVALID", "任务执行器配置不合法", HttpStatus.INTERNAL_SERVER_ERROR),

    MQ_SEND_FAILED("MQ_SEND_FAILED", "消息发送失败", HttpStatus.INTERNAL_SERVER_ERROR),
    MQ_CONSUME_FAILED("MQ_CONSUME_FAILED", "消息消费失败", HttpStatus.INTERNAL_SERVER_ERROR),
    MQ_MESSAGE_INVALID("MQ_MESSAGE_INVALID", "消息内容不合法", HttpStatus.BAD_REQUEST),
    MQ_CONFIGURATION_INVALID("MQ_CONFIGURATION_INVALID", "消息队列配置不合法", HttpStatus.INTERNAL_SERVER_ERROR),

    MEDIA_INPUT_INVALID("MEDIA_INPUT_INVALID", "Media input file is invalid", HttpStatus.BAD_REQUEST),
    MEDIA_OUTPUT_INVALID("MEDIA_OUTPUT_INVALID", "Media output path is invalid", HttpStatus.BAD_REQUEST),
    MEDIA_CONFIGURATION_INVALID("MEDIA_CONFIGURATION_INVALID", "Media processing configuration is invalid", HttpStatus.INTERNAL_SERVER_ERROR),
    MEDIA_FFMPEG_FAILED("MEDIA_FFMPEG_FAILED", "FFmpeg audio extraction failed", HttpStatus.INTERNAL_SERVER_ERROR),
    MEDIA_FFMPEG_TIMEOUT("MEDIA_FFMPEG_TIMEOUT", "FFmpeg audio extraction timed out", HttpStatus.GATEWAY_TIMEOUT),
    MEDIA_PLAYBACK_TOKEN_INVALID("MEDIA_PLAYBACK_TOKEN_INVALID", "Media playback token is invalid", HttpStatus.UNAUTHORIZED),
    MEDIA_PLAYBACK_TOKEN_EXPIRED("MEDIA_PLAYBACK_TOKEN_EXPIRED", "Media playback token has expired", HttpStatus.UNAUTHORIZED),
    MEDIA_PLAYBACK_FORBIDDEN("MEDIA_PLAYBACK_FORBIDDEN", "Media playback is forbidden", HttpStatus.FORBIDDEN),
    MEDIA_SOURCE_NOT_FOUND("MEDIA_SOURCE_NOT_FOUND", "Media source is not available", HttpStatus.NOT_FOUND),
    MEDIA_RANGE_NOT_SATISFIABLE("MEDIA_RANGE_NOT_SATISFIABLE", "Media range is not satisfiable", HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE),
    MEDIA_SUBTITLE_PROBE_FAILED("MEDIA_SUBTITLE_PROBE_FAILED", "Embedded subtitle probe failed", HttpStatus.INTERNAL_SERVER_ERROR),
    MEDIA_SUBTITLE_UNSUPPORTED("MEDIA_SUBTITLE_UNSUPPORTED", "Embedded subtitle format is not supported", HttpStatus.UNPROCESSABLE_ENTITY),
    MEDIA_SUBTITLE_EXTRACTION_FAILED("MEDIA_SUBTITLE_EXTRACTION_FAILED", "Embedded subtitle extraction failed", HttpStatus.INTERNAL_SERVER_ERROR),

    AI_PROVIDER_TIMEOUT("AI_PROVIDER_TIMEOUT", "AI Provider 调用超时", HttpStatus.GATEWAY_TIMEOUT),
    AI_PROVIDER_FAILED("AI_PROVIDER_FAILED", "AI Provider 调用失败", HttpStatus.BAD_GATEWAY),

    ARTIFACT_NOT_FOUND("ARTIFACT_NOT_FOUND", "制品不存在", HttpStatus.NOT_FOUND);

    private final String code;
    private final String defaultMessage;
    private final HttpStatus httpStatus;

    ErrorCode(String code, String defaultMessage, HttpStatus httpStatus) {
        this.code = code;
        this.defaultMessage = defaultMessage;
        this.httpStatus = httpStatus;
    }

    public String code() {
        return code;
    }

    public String defaultMessage() {
        return defaultMessage;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
